mysql_root_password: devopsmaonamassa
mysql_databases:
  - name: notes
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: notesapp
    host: "%"
    password: devopsmaonamassa
    priv: "notes.*:ALL"